addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"    % "0.4.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"    % "2.4.6")
addSbtPlugin("com.typesafe"              % "sbt-mima-plugin" % "1.1.1")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"   % "2.4.0")
addSbtPlugin("com.github.sbt"            % "sbt-site"        % "1.7.0")
addSbtPlugin("org.scoverage"             % "sbt-coveralls"   % "1.3.2")
addSbtPlugin("com.github.sbt"            % "sbt-ci-release"  % "1.11.2")
