name: RELEASE

on:
  push:
    tags:
      - '*'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: coursier/cache-action@v6

    - name: Install sbt
      uses: sbt/setup-sbt@v1

    - name: Make site
      run: sbt makeSite

    - name: Publish ScalaDoc
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: gh-pages
        folder: modules/core/target/site
        clean: false

  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [data, core, http4s]
    steps:
    - uses: actions/checkout@v5
    - uses: coursier/cache-action@v6

    - name: Install sbt
      uses: sbt/setup-sbt@v1

    - name: Deploy ${{ matrix.module }} to Maven Central
      run: sbt "project ${{ matrix.module }}" ci-release
      env:
        PGP_PASSPHRASE: ${{ secrets.SONA_PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.SONA_PGP_SECRET }}
        SONATYPE_USERNAME: ${{ secrets.SONA_USER }}
        SONATYPE_PASSWORD: ${{ secrets.SONA_PASS }}